server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://0.0.0.0:5332/customer
    username: damian
    password: password
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop



